hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
      employee-service:
          path: /employees/**
          url: http://127.0.0.1:8000
          stripPrefix: false
          sensitiveHeaders:
      auth-service:
          path: /uaa/**
          url: http://127.0.0.1:5000
          stripPrefix: false
          sensitiveHeaders:
      resource-service:
          path: /resources/**
          url: http://127.0.0.1:7000
          stripPrefix: false
          sensitiveHeaders:


server:
  port: 4000