security:
  oauth2:
    client:
      clientId: resource-service
      clientSecret: ${RESOURCE_SERVICE_PASSWORD}
      accessTokenUri: http://127.0.0.1:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /resources
  port: 7000

spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: fintechlabs-portal
      port: 27017